//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTEWithASPNETCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminLTEWithASPNETCore.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enrico.rossini.uk@live.com.
        /// </summary>
        public static string APIContactEmail {
            get {
                return ResourceManager.GetString("APIContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrico Rossini.
        /// </summary>
        public static string APIContactName {
            get {
                return ResourceManager.GetString("APIContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.puresourcecode.com/contact-us.
        /// </summary>
        public static string APIContactUrl {
            get {
                return ResourceManager.GetString("APIContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the application is running in debug mode, PureSourceCode (PSC) AdminLTE shows all the available APIs via Swagger. Swagger (OpenAPI) is a language-agnostic specification for describing REST APIs. It allows both computers and humans to understand the capabilities of a REST API without direct access to the source code..
        /// </summary>
        public static string APIDescription {
            get {
                return ResourceManager.GetString("APIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PureSourceCode AdminLTE APIs.
        /// </summary>
        public static string APITitle {
            get {
                return ResourceManager.GetString("APITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PureSourceCode AdminLTE v1.
        /// </summary>
        public static string APITitleV1 {
            get {
                return ResourceManager.GetString("APITitleV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs dashboard.
        /// </summary>
        public static string JobDashboardTitle {
            get {
                return ResourceManager.GetString("JobDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.
        /// </summary>
        public static string V1 {
            get {
                return ResourceManager.GetString("V1", resourceCulture);
            }
        }
    }
}
