// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSC.Persistence;

namespace PSC.Persistence.Migrations
{
    [DbContext(typeof(PSCContext))]
    [Migration("20210331135753_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PSC.Domain.Audit.AuditAzureCost", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("AzureCostImportId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cost")
                        .HasPrecision(24, 20)
                        .HasColumnType("decimal(24,20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(24, 20)
                        .HasColumnType("decimal(24,20)");

                    b.Property<long>("ResourceGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubcategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_AzureCosts");
                });

            modelBuilder.Entity("PSC.Domain.Audit.AuditAzureCostImport", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_AzureCostImports");
                });

            modelBuilder.Entity("PSC.Domain.Audit.AuditAzureCostImportLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("AzureCostImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LogData")
                        .HasColumnType("datetime2");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_AzureCostImportLogs");
                });

            modelBuilder.Entity("PSC.Domain.Audit.CommonTables.AuditAzureCategory", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_tbl_AzureCategories");
                });

            modelBuilder.Entity("PSC.Domain.Audit.CommonTables.AuditAzureLocation", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_tbl_AzureLocations");
                });

            modelBuilder.Entity("PSC.Domain.Audit.CommonTables.AuditAzureResource", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_tbl_AzureResources");
                });

            modelBuilder.Entity("PSC.Domain.Audit.CommonTables.AuditAzureResourceGroup", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_tbl_AzureResourceGroups");
                });

            modelBuilder.Entity("PSC.Domain.Audit.CommonTables.AuditAzureSubcategory", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_tbl_AzureSubcategories");
                });

            modelBuilder.Entity("PSC.Domain.Audit.CommonTables.AuditCountry", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_tbl_Countries");
                });

            modelBuilder.Entity("PSC.Domain.AzureCost", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AzureCostImportId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cost")
                        .HasPrecision(24, 20)
                        .HasColumnType("decimal(24,20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(24, 20)
                        .HasColumnType("decimal(24,20)");

                    b.Property<long?>("ResourceGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubcategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("AzureCostImportId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ResourceGroupId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("AzureCosts");
                });

            modelBuilder.Entity("PSC.Domain.AzureCostImport", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AzureCostImports");
                });

            modelBuilder.Entity("PSC.Domain.AzureCostImportLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AzureCostImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogData")
                        .HasColumnType("datetime2");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AzureCostImportId");

                    b.ToTable("AzureCostImportLogs");
                });

            modelBuilder.Entity("PSC.Domain.CommonTables.AzureCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_AzureCategories");
                });

            modelBuilder.Entity("PSC.Domain.CommonTables.AzureLocation", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_AzureLocations");
                });

            modelBuilder.Entity("PSC.Domain.CommonTables.AzureResource", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_AzureResources");
                });

            modelBuilder.Entity("PSC.Domain.CommonTables.AzureResourceGroup", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_AzureResourceGroups");
                });

            modelBuilder.Entity("PSC.Domain.CommonTables.AzureSubcategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_AzureSubcategories");
                });

            modelBuilder.Entity("PSC.Domain.CommonTables.Country", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("tbl_Countries");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 631, DateTimeKind.Local).AddTicks(224),
                            Name = "Afghanistan",
                            Order = 0
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(4906),
                            Name = "Albania",
                            Order = 0
                        },
                        new
                        {
                            ID = 3L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5019),
                            Name = "Algeria",
                            Order = 0
                        },
                        new
                        {
                            ID = 4L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5031),
                            Name = "Andorra",
                            Order = 0
                        },
                        new
                        {
                            ID = 5L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5040),
                            Name = "Angola",
                            Order = 0
                        },
                        new
                        {
                            ID = 6L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5049),
                            Name = "Antigua and Barbuda",
                            Order = 0
                        },
                        new
                        {
                            ID = 7L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5074),
                            Name = "Argentina",
                            Order = 0
                        },
                        new
                        {
                            ID = 8L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5084),
                            Name = "Armenia",
                            Order = 0
                        },
                        new
                        {
                            ID = 9L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5092),
                            Name = "Australia",
                            Order = 0
                        },
                        new
                        {
                            ID = 10L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5100),
                            Name = "Austria",
                            Order = 0
                        },
                        new
                        {
                            ID = 11L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5109),
                            Name = "Azerbaijan",
                            Order = 0
                        },
                        new
                        {
                            ID = 12L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5117),
                            Name = "The Bahamas",
                            Order = 0
                        },
                        new
                        {
                            ID = 13L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5138),
                            Name = "Bahrain",
                            Order = 0
                        },
                        new
                        {
                            ID = 14L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5147),
                            Name = "Bangladesh",
                            Order = 0
                        },
                        new
                        {
                            ID = 15L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5156),
                            Name = "Barbados",
                            Order = 0
                        },
                        new
                        {
                            ID = 16L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5164),
                            Name = "Belarus",
                            Order = 0
                        },
                        new
                        {
                            ID = 17L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5172),
                            Name = "Belgium",
                            Order = 0
                        },
                        new
                        {
                            ID = 18L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5179),
                            Name = "Belize",
                            Order = 0
                        },
                        new
                        {
                            ID = 19L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5187),
                            Name = "Benin",
                            Order = 0
                        },
                        new
                        {
                            ID = 20L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5195),
                            Name = "Bhutan",
                            Order = 0
                        },
                        new
                        {
                            ID = 21L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5204),
                            Name = "Bolivia",
                            Order = 0
                        },
                        new
                        {
                            ID = 22L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5212),
                            Name = "Bosnia and Herzegovina",
                            Order = 0
                        },
                        new
                        {
                            ID = 23L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5220),
                            Name = "Botswana",
                            Order = 0
                        },
                        new
                        {
                            ID = 24L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5228),
                            Name = "Brazil",
                            Order = 0
                        },
                        new
                        {
                            ID = 25L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5236),
                            Name = "Brunei",
                            Order = 0
                        },
                        new
                        {
                            ID = 26L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5244),
                            Name = "Bulgaria",
                            Order = 0
                        },
                        new
                        {
                            ID = 27L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5251),
                            Name = "Burkina Faso",
                            Order = 0
                        },
                        new
                        {
                            ID = 28L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5259),
                            Name = "Burundi",
                            Order = 0
                        },
                        new
                        {
                            ID = 29L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5267),
                            Name = "Cambodia",
                            Order = 0
                        },
                        new
                        {
                            ID = 30L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5275),
                            Name = "Cameroon",
                            Order = 0
                        },
                        new
                        {
                            ID = 31L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5283),
                            Name = "Canada",
                            Order = 0
                        },
                        new
                        {
                            ID = 32L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5290),
                            Name = "Cape Verde",
                            Order = 0
                        },
                        new
                        {
                            ID = 33L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5298),
                            Name = "Central African Republic",
                            Order = 0
                        },
                        new
                        {
                            ID = 34L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5306),
                            Name = "Chad",
                            Order = 0
                        },
                        new
                        {
                            ID = 35L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5314),
                            Name = "Chile",
                            Order = 0
                        },
                        new
                        {
                            ID = 36L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5322),
                            Name = "China",
                            Order = 0
                        },
                        new
                        {
                            ID = 37L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5330),
                            Name = "Colombia",
                            Order = 0
                        },
                        new
                        {
                            ID = 38L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5338),
                            Name = "Comoros",
                            Order = 0
                        },
                        new
                        {
                            ID = 39L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5346),
                            Name = "Congo, Republic of the",
                            Order = 0
                        },
                        new
                        {
                            ID = 40L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5355),
                            Name = "Congo, Democratic Republic of the",
                            Order = 0
                        },
                        new
                        {
                            ID = 41L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5364),
                            Name = "Costa Rica",
                            Order = 0
                        },
                        new
                        {
                            ID = 42L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5372),
                            Name = "Cote d'Ivoire",
                            Order = 0
                        },
                        new
                        {
                            ID = 43L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5379),
                            Name = "Croatia",
                            Order = 0
                        },
                        new
                        {
                            ID = 44L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5388),
                            Name = "Cuba",
                            Order = 0
                        },
                        new
                        {
                            ID = 45L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5395),
                            Name = "Cyprus",
                            Order = 0
                        },
                        new
                        {
                            ID = 46L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5403),
                            Name = "Czech Republic",
                            Order = 0
                        },
                        new
                        {
                            ID = 47L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5411),
                            Name = "Denmark",
                            Order = 0
                        },
                        new
                        {
                            ID = 48L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5419),
                            Name = "Djibouti",
                            Order = 0
                        },
                        new
                        {
                            ID = 49L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5427),
                            Name = "Dominica",
                            Order = 0
                        },
                        new
                        {
                            ID = 50L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5434),
                            Name = "Dominican Republic",
                            Order = 0
                        },
                        new
                        {
                            ID = 51L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5442),
                            Name = "East Timor (Timor-Leste)",
                            Order = 0
                        },
                        new
                        {
                            ID = 52L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5450),
                            Name = "Ecuador",
                            Order = 0
                        },
                        new
                        {
                            ID = 53L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5458),
                            Name = "Egypt",
                            Order = 0
                        },
                        new
                        {
                            ID = 54L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5466),
                            Name = "El Salvador",
                            Order = 0
                        },
                        new
                        {
                            ID = 55L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5474),
                            Name = "Equatorial Guinea",
                            Order = 0
                        },
                        new
                        {
                            ID = 56L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5481),
                            Name = "Eritrea",
                            Order = 0
                        },
                        new
                        {
                            ID = 57L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5489),
                            Name = "Estonia",
                            Order = 0
                        },
                        new
                        {
                            ID = 58L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5497),
                            Name = "Ethiopia",
                            Order = 0
                        },
                        new
                        {
                            ID = 59L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5505),
                            Name = "Fiji",
                            Order = 0
                        },
                        new
                        {
                            ID = 60L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5513),
                            Name = "Finland",
                            Order = 0
                        },
                        new
                        {
                            ID = 61L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5521),
                            Name = "France",
                            Order = 0
                        },
                        new
                        {
                            ID = 62L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5528),
                            Name = "Gabon",
                            Order = 0
                        },
                        new
                        {
                            ID = 63L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5536),
                            Name = "The Gambia",
                            Order = 0
                        },
                        new
                        {
                            ID = 64L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5544),
                            Name = "Georgia",
                            Order = 0
                        },
                        new
                        {
                            ID = 65L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5552),
                            Name = "Germany",
                            Order = 0
                        },
                        new
                        {
                            ID = 66L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5560),
                            Name = "Ghana",
                            Order = 0
                        },
                        new
                        {
                            ID = 67L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5567),
                            Name = "Greece",
                            Order = 0
                        },
                        new
                        {
                            ID = 68L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5575),
                            Name = "Grenada",
                            Order = 0
                        },
                        new
                        {
                            ID = 69L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5583),
                            Name = "Guatemala",
                            Order = 0
                        },
                        new
                        {
                            ID = 70L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5590),
                            Name = "Guinea",
                            Order = 0
                        },
                        new
                        {
                            ID = 71L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5598),
                            Name = "Guinea-Bissau",
                            Order = 0
                        },
                        new
                        {
                            ID = 72L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5606),
                            Name = "Guyana",
                            Order = 0
                        },
                        new
                        {
                            ID = 73L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5614),
                            Name = "Haiti",
                            Order = 0
                        },
                        new
                        {
                            ID = 74L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5621),
                            Name = "Honduras",
                            Order = 0
                        },
                        new
                        {
                            ID = 75L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5629),
                            Name = "Hungary",
                            Order = 0
                        },
                        new
                        {
                            ID = 76L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5637),
                            Name = "Iceland",
                            Order = 0
                        },
                        new
                        {
                            ID = 77L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5645),
                            Name = "India",
                            Order = 0
                        },
                        new
                        {
                            ID = 78L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5652),
                            Name = "Indonesia",
                            Order = 0
                        },
                        new
                        {
                            ID = 79L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5660),
                            Name = "Iran",
                            Order = 0
                        },
                        new
                        {
                            ID = 80L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5668),
                            Name = "Iraq",
                            Order = 0
                        },
                        new
                        {
                            ID = 81L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5675),
                            Name = "Ireland",
                            Order = 0
                        },
                        new
                        {
                            ID = 82L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5776),
                            Name = "Israel",
                            Order = 0
                        },
                        new
                        {
                            ID = 83L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5787),
                            Name = "Italy",
                            Order = 0
                        },
                        new
                        {
                            ID = 84L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5795),
                            Name = "Jamaica",
                            Order = 0
                        },
                        new
                        {
                            ID = 85L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5803),
                            Name = "Japan",
                            Order = 0
                        },
                        new
                        {
                            ID = 86L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5811),
                            Name = "Jordan",
                            Order = 0
                        },
                        new
                        {
                            ID = 87L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5819),
                            Name = "Kazakhstan",
                            Order = 0
                        },
                        new
                        {
                            ID = 88L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5827),
                            Name = "Kenya",
                            Order = 0
                        },
                        new
                        {
                            ID = 89L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5835),
                            Name = "Kiribati",
                            Order = 0
                        },
                        new
                        {
                            ID = 90L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5843),
                            Name = "Korea, North",
                            Order = 0
                        },
                        new
                        {
                            ID = 91L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5851),
                            Name = "Korea, South",
                            Order = 0
                        },
                        new
                        {
                            ID = 92L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5859),
                            Name = "Kosovo",
                            Order = 0
                        },
                        new
                        {
                            ID = 93L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5868),
                            Name = "Kuwait",
                            Order = 0
                        },
                        new
                        {
                            ID = 94L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5875),
                            Name = "Kyrgyzstan",
                            Order = 0
                        },
                        new
                        {
                            ID = 95L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5884),
                            Name = "Laos",
                            Order = 0
                        },
                        new
                        {
                            ID = 96L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5892),
                            Name = "Latvia",
                            Order = 0
                        },
                        new
                        {
                            ID = 97L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5899),
                            Name = "Lebanon",
                            Order = 0
                        },
                        new
                        {
                            ID = 98L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5907),
                            Name = "Lesotho",
                            Order = 0
                        },
                        new
                        {
                            ID = 99L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5915),
                            Name = "Liberia",
                            Order = 0
                        },
                        new
                        {
                            ID = 100L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5923),
                            Name = "Libya",
                            Order = 0
                        },
                        new
                        {
                            ID = 101L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5931),
                            Name = "Liechtenstein",
                            Order = 0
                        },
                        new
                        {
                            ID = 102L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5939),
                            Name = "Lithuania",
                            Order = 0
                        },
                        new
                        {
                            ID = 103L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5947),
                            Name = "Luxembourg",
                            Order = 0
                        },
                        new
                        {
                            ID = 104L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5955),
                            Name = "Macedonia",
                            Order = 0
                        },
                        new
                        {
                            ID = 105L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5963),
                            Name = "Madagascar",
                            Order = 0
                        },
                        new
                        {
                            ID = 106L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5970),
                            Name = "Malawi",
                            Order = 0
                        },
                        new
                        {
                            ID = 107L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5978),
                            Name = "Malaysia",
                            Order = 0
                        },
                        new
                        {
                            ID = 108L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5986),
                            Name = "Maldives",
                            Order = 0
                        },
                        new
                        {
                            ID = 109L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(5994),
                            Name = "Mali",
                            Order = 0
                        },
                        new
                        {
                            ID = 110L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6003),
                            Name = "Malta",
                            Order = 0
                        },
                        new
                        {
                            ID = 111L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6010),
                            Name = "Marshall Islands",
                            Order = 0
                        },
                        new
                        {
                            ID = 112L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6018),
                            Name = "Mauritania",
                            Order = 0
                        },
                        new
                        {
                            ID = 113L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6026),
                            Name = "Mauritius",
                            Order = 0
                        },
                        new
                        {
                            ID = 114L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6034),
                            Name = "Mexico",
                            Order = 0
                        },
                        new
                        {
                            ID = 115L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6042),
                            Name = "Micronesia, Federated States of",
                            Order = 0
                        },
                        new
                        {
                            ID = 116L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6049),
                            Name = "Moldova",
                            Order = 0
                        },
                        new
                        {
                            ID = 117L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6057),
                            Name = "Monaco",
                            Order = 0
                        },
                        new
                        {
                            ID = 118L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6065),
                            Name = "Mongolia",
                            Order = 0
                        },
                        new
                        {
                            ID = 119L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6073),
                            Name = "Montenegro",
                            Order = 0
                        },
                        new
                        {
                            ID = 120L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6081),
                            Name = "Morocco",
                            Order = 0
                        },
                        new
                        {
                            ID = 121L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6088),
                            Name = "Mozambique",
                            Order = 0
                        },
                        new
                        {
                            ID = 122L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6096),
                            Name = "Myanmar (Burma)",
                            Order = 0
                        },
                        new
                        {
                            ID = 123L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6104),
                            Name = "Namibia",
                            Order = 0
                        },
                        new
                        {
                            ID = 124L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6111),
                            Name = "Nauru",
                            Order = 0
                        },
                        new
                        {
                            ID = 125L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6119),
                            Name = "Nepal",
                            Order = 0
                        },
                        new
                        {
                            ID = 126L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6127),
                            Name = "Netherlands",
                            Order = 0
                        },
                        new
                        {
                            ID = 127L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6135),
                            Name = "New Zealand",
                            Order = 0
                        },
                        new
                        {
                            ID = 128L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6142),
                            Name = "Nicaragua",
                            Order = 0
                        },
                        new
                        {
                            ID = 129L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6150),
                            Name = "Niger",
                            Order = 0
                        },
                        new
                        {
                            ID = 130L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6158),
                            Name = "Nigeria",
                            Order = 0
                        },
                        new
                        {
                            ID = 131L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6166),
                            Name = "Norway",
                            Order = 0
                        },
                        new
                        {
                            ID = 132L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6174),
                            Name = "Oman",
                            Order = 0
                        },
                        new
                        {
                            ID = 133L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6181),
                            Name = "Pakistan",
                            Order = 0
                        },
                        new
                        {
                            ID = 134L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6189),
                            Name = "Palau",
                            Order = 0
                        },
                        new
                        {
                            ID = 135L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6197),
                            Name = "Panama",
                            Order = 0
                        },
                        new
                        {
                            ID = 136L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6205),
                            Name = "Papua New Guinea",
                            Order = 0
                        },
                        new
                        {
                            ID = 137L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6213),
                            Name = "Paraguay",
                            Order = 0
                        },
                        new
                        {
                            ID = 138L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6221),
                            Name = "Peru",
                            Order = 0
                        },
                        new
                        {
                            ID = 139L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6228),
                            Name = "Philippines",
                            Order = 0
                        },
                        new
                        {
                            ID = 140L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6236),
                            Name = "Poland",
                            Order = 0
                        },
                        new
                        {
                            ID = 141L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6244),
                            Name = "Portugal",
                            Order = 0
                        },
                        new
                        {
                            ID = 142L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6252),
                            Name = "Qatar",
                            Order = 0
                        },
                        new
                        {
                            ID = 143L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6259),
                            Name = "Romania",
                            Order = 0
                        },
                        new
                        {
                            ID = 144L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6267),
                            Name = "Russia",
                            Order = 0
                        },
                        new
                        {
                            ID = 145L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6274),
                            Name = "Rwanda",
                            Order = 0
                        },
                        new
                        {
                            ID = 146L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6282),
                            Name = "Saint Kitts and Nevis",
                            Order = 0
                        },
                        new
                        {
                            ID = 147L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6290),
                            Name = "Saint Lucia",
                            Order = 0
                        },
                        new
                        {
                            ID = 148L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6298),
                            Name = "Saint Vincent and the Grenadines",
                            Order = 0
                        },
                        new
                        {
                            ID = 149L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6306),
                            Name = "Samoa",
                            Order = 0
                        },
                        new
                        {
                            ID = 150L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6313),
                            Name = "San Marino",
                            Order = 0
                        },
                        new
                        {
                            ID = 151L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6321),
                            Name = "Sao Tome and Principe",
                            Order = 0
                        },
                        new
                        {
                            ID = 152L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6329),
                            Name = "Saudi Arabia",
                            Order = 0
                        },
                        new
                        {
                            ID = 153L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6336),
                            Name = "Senegal",
                            Order = 0
                        },
                        new
                        {
                            ID = 154L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6344),
                            Name = "Serbia",
                            Order = 0
                        },
                        new
                        {
                            ID = 155L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6352),
                            Name = "Seychelles",
                            Order = 0
                        },
                        new
                        {
                            ID = 156L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6360),
                            Name = "Sierra Leone",
                            Order = 0
                        },
                        new
                        {
                            ID = 157L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6367),
                            Name = "Singapore",
                            Order = 0
                        },
                        new
                        {
                            ID = 158L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6375),
                            Name = "Slovakia",
                            Order = 0
                        },
                        new
                        {
                            ID = 159L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6382),
                            Name = "Slovenia",
                            Order = 0
                        },
                        new
                        {
                            ID = 160L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6390),
                            Name = "Solomon Islands",
                            Order = 0
                        },
                        new
                        {
                            ID = 161L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6398),
                            Name = "Somalia",
                            Order = 0
                        },
                        new
                        {
                            ID = 162L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6406),
                            Name = "South Africa",
                            Order = 0
                        },
                        new
                        {
                            ID = 163L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6414),
                            Name = "South Sudan",
                            Order = 0
                        },
                        new
                        {
                            ID = 164L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6421),
                            Name = "Spain",
                            Order = 0
                        },
                        new
                        {
                            ID = 165L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6429),
                            Name = "Sri Lanka",
                            Order = 0
                        },
                        new
                        {
                            ID = 166L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6437),
                            Name = "Sudan",
                            Order = 0
                        },
                        new
                        {
                            ID = 167L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6444),
                            Name = "Suriname",
                            Order = 0
                        },
                        new
                        {
                            ID = 168L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6452),
                            Name = "Swaziland",
                            Order = 0
                        },
                        new
                        {
                            ID = 169L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6460),
                            Name = "Sweden",
                            Order = 0
                        },
                        new
                        {
                            ID = 170L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6468),
                            Name = "Switzerland",
                            Order = 0
                        },
                        new
                        {
                            ID = 171L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6475),
                            Name = "Syria",
                            Order = 0
                        },
                        new
                        {
                            ID = 172L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6483),
                            Name = "Taiwan",
                            Order = 0
                        },
                        new
                        {
                            ID = 173L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6491),
                            Name = "Tajikistan",
                            Order = 0
                        },
                        new
                        {
                            ID = 174L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6499),
                            Name = "Tanzania",
                            Order = 0
                        },
                        new
                        {
                            ID = 175L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6507),
                            Name = "Thailand",
                            Order = 0
                        },
                        new
                        {
                            ID = 176L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6514),
                            Name = "Togo",
                            Order = 0
                        },
                        new
                        {
                            ID = 177L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6522),
                            Name = "Tonga",
                            Order = 0
                        },
                        new
                        {
                            ID = 178L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6530),
                            Name = "Trinidad and Tobago",
                            Order = 0
                        },
                        new
                        {
                            ID = 179L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6538),
                            Name = "Tunisia",
                            Order = 0
                        },
                        new
                        {
                            ID = 180L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6545),
                            Name = "Turkey",
                            Order = 0
                        },
                        new
                        {
                            ID = 181L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6553),
                            Name = "Turkmenistan",
                            Order = 0
                        },
                        new
                        {
                            ID = 182L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6561),
                            Name = "Tuvalu",
                            Order = 0
                        },
                        new
                        {
                            ID = 183L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6569),
                            Name = "Uganda",
                            Order = 0
                        },
                        new
                        {
                            ID = 184L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6753),
                            Name = "Ukraine",
                            Order = 0
                        },
                        new
                        {
                            ID = 185L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6764),
                            Name = "United Arab Emirates",
                            Order = 0
                        },
                        new
                        {
                            ID = 186L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(6773),
                            Name = "United Kingdom",
                            Order = 1
                        },
                        new
                        {
                            ID = 187L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8322),
                            Name = "United States of America",
                            Order = 1
                        },
                        new
                        {
                            ID = 188L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8356),
                            Name = "Uruguay",
                            Order = 0
                        },
                        new
                        {
                            ID = 189L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8364),
                            Name = "Uzbekistan",
                            Order = 0
                        },
                        new
                        {
                            ID = 190L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8372),
                            Name = "Vanuatu",
                            Order = 0
                        },
                        new
                        {
                            ID = 191L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8380),
                            Name = "Vatican City (Holy See)",
                            Order = 0
                        },
                        new
                        {
                            ID = 192L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8387),
                            Name = "Venezuela",
                            Order = 0
                        },
                        new
                        {
                            ID = 193L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8395),
                            Name = "Vietnam",
                            Order = 0
                        },
                        new
                        {
                            ID = 194L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8403),
                            Name = "Yemen",
                            Order = 0
                        },
                        new
                        {
                            ID = 195L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8411),
                            Name = "Zambia",
                            Order = 0
                        },
                        new
                        {
                            ID = 196L,
                            CreatedAt = new DateTime(2021, 3, 31, 14, 57, 52, 637, DateTimeKind.Local).AddTicks(8419),
                            Name = "Zimbabwe",
                            Order = 0
                        });
                });

            modelBuilder.Entity("PSC.Domain.AzureCost", b =>
                {
                    b.HasOne("PSC.Domain.AzureCostImport", "AzureCostImport")
                        .WithMany()
                        .HasForeignKey("AzureCostImportId");

                    b.HasOne("PSC.Domain.CommonTables.AzureCategory", "AzureCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("PSC.Domain.CommonTables.AzureLocation", "AzureLocation")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("PSC.Domain.CommonTables.AzureResourceGroup", "AzureResourceGroup")
                        .WithMany()
                        .HasForeignKey("ResourceGroupId");

                    b.HasOne("PSC.Domain.CommonTables.AzureResource", "AzureResource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.HasOne("PSC.Domain.CommonTables.AzureSubcategory", "AzureSubcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId");

                    b.Navigation("AzureCategory");

                    b.Navigation("AzureCostImport");

                    b.Navigation("AzureLocation");

                    b.Navigation("AzureResource");

                    b.Navigation("AzureResourceGroup");

                    b.Navigation("AzureSubcategory");
                });

            modelBuilder.Entity("PSC.Domain.AzureCostImportLog", b =>
                {
                    b.HasOne("PSC.Domain.AzureCostImport", "AzureCostImport")
                        .WithMany("ImportLogs")
                        .HasForeignKey("AzureCostImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzureCostImport");
                });

            modelBuilder.Entity("PSC.Domain.AzureCostImport", b =>
                {
                    b.Navigation("ImportLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
