// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSC.Repositories;

namespace PSC.Repositories.Migrations
{
    [DbContext(typeof(PSCContext))]
    partial class PSCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PSC.Domain.Audit.AuditMessage", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdMessage")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_Messages");
                });

            modelBuilder.Entity("PSC.Domain.Audit.CommonTables.AuditCountry", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IDCountry")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audit_Countries");
                });

            modelBuilder.Entity("PSC.Domain.CommonTables.Country", b =>
                {
                    b.Property<long>("IDCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("IDCountry");

                    b.ToTable("tbl_Countries");

                    b.HasData(
                        new
                        {
                            IDCountry = 1L,
                            Name = "Afghanistan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 2L,
                            Name = "Albania",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 3L,
                            Name = "Algeria",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 4L,
                            Name = "Andorra",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 5L,
                            Name = "Angola",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 6L,
                            Name = "Antigua and Barbuda",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 7L,
                            Name = "Argentina",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 8L,
                            Name = "Armenia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 9L,
                            Name = "Australia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 10L,
                            Name = "Austria",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 11L,
                            Name = "Azerbaijan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 12L,
                            Name = "The Bahamas",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 13L,
                            Name = "Bahrain",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 14L,
                            Name = "Bangladesh",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 15L,
                            Name = "Barbados",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 16L,
                            Name = "Belarus",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 17L,
                            Name = "Belgium",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 18L,
                            Name = "Belize",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 19L,
                            Name = "Benin",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 20L,
                            Name = "Bhutan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 21L,
                            Name = "Bolivia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 22L,
                            Name = "Bosnia and Herzegovina",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 23L,
                            Name = "Botswana",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 24L,
                            Name = "Brazil",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 25L,
                            Name = "Brunei",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 26L,
                            Name = "Bulgaria",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 27L,
                            Name = "Burkina Faso",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 28L,
                            Name = "Burundi",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 29L,
                            Name = "Cambodia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 30L,
                            Name = "Cameroon",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 31L,
                            Name = "Canada",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 32L,
                            Name = "Cape Verde",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 33L,
                            Name = "Central African Republic",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 34L,
                            Name = "Chad",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 35L,
                            Name = "Chile",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 36L,
                            Name = "China",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 37L,
                            Name = "Colombia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 38L,
                            Name = "Comoros",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 39L,
                            Name = "Congo, Republic of the",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 40L,
                            Name = "Congo, Democratic Republic of the",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 41L,
                            Name = "Costa Rica",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 42L,
                            Name = "Cote d'Ivoire",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 43L,
                            Name = "Croatia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 44L,
                            Name = "Cuba",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 45L,
                            Name = "Cyprus",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 46L,
                            Name = "Czech Republic",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 47L,
                            Name = "Denmark",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 48L,
                            Name = "Djibouti",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 49L,
                            Name = "Dominica",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 50L,
                            Name = "Dominican Republic",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 51L,
                            Name = "East Timor (Timor-Leste)",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 52L,
                            Name = "Ecuador",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 53L,
                            Name = "Egypt",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 54L,
                            Name = "El Salvador",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 55L,
                            Name = "Equatorial Guinea",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 56L,
                            Name = "Eritrea",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 57L,
                            Name = "Estonia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 58L,
                            Name = "Ethiopia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 59L,
                            Name = "Fiji",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 60L,
                            Name = "Finland",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 61L,
                            Name = "France",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 62L,
                            Name = "Gabon",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 63L,
                            Name = "The Gambia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 64L,
                            Name = "Georgia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 65L,
                            Name = "Germany",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 66L,
                            Name = "Ghana",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 67L,
                            Name = "Greece",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 68L,
                            Name = "Grenada",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 69L,
                            Name = "Guatemala",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 70L,
                            Name = "Guinea",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 71L,
                            Name = "Guinea-Bissau",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 72L,
                            Name = "Guyana",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 73L,
                            Name = "Haiti",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 74L,
                            Name = "Honduras",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 75L,
                            Name = "Hungary",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 76L,
                            Name = "Iceland",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 77L,
                            Name = "India",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 78L,
                            Name = "Indonesia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 79L,
                            Name = "Iran",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 80L,
                            Name = "Iraq",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 81L,
                            Name = "Ireland",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 82L,
                            Name = "Israel",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 83L,
                            Name = "Italy",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 84L,
                            Name = "Jamaica",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 85L,
                            Name = "Japan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 86L,
                            Name = "Jordan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 87L,
                            Name = "Kazakhstan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 88L,
                            Name = "Kenya",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 89L,
                            Name = "Kiribati",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 90L,
                            Name = "Korea, North",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 91L,
                            Name = "Korea, South",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 92L,
                            Name = "Kosovo",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 93L,
                            Name = "Kuwait",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 94L,
                            Name = "Kyrgyzstan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 95L,
                            Name = "Laos",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 96L,
                            Name = "Latvia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 97L,
                            Name = "Lebanon",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 98L,
                            Name = "Lesotho",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 99L,
                            Name = "Liberia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 100L,
                            Name = "Libya",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 101L,
                            Name = "Liechtenstein",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 102L,
                            Name = "Lithuania",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 103L,
                            Name = "Luxembourg",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 104L,
                            Name = "Macedonia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 105L,
                            Name = "Madagascar",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 106L,
                            Name = "Malawi",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 107L,
                            Name = "Malaysia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 108L,
                            Name = "Maldives",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 109L,
                            Name = "Mali",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 110L,
                            Name = "Malta",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 111L,
                            Name = "Marshall Islands",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 112L,
                            Name = "Mauritania",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 113L,
                            Name = "Mauritius",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 114L,
                            Name = "Mexico",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 115L,
                            Name = "Micronesia, Federated States of",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 116L,
                            Name = "Moldova",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 117L,
                            Name = "Monaco",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 118L,
                            Name = "Mongolia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 119L,
                            Name = "Montenegro",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 120L,
                            Name = "Morocco",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 121L,
                            Name = "Mozambique",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 122L,
                            Name = "Myanmar (Burma)",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 123L,
                            Name = "Namibia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 124L,
                            Name = "Nauru",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 125L,
                            Name = "Nepal",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 126L,
                            Name = "Netherlands",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 127L,
                            Name = "New Zealand",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 128L,
                            Name = "Nicaragua",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 129L,
                            Name = "Niger",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 130L,
                            Name = "Nigeria",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 131L,
                            Name = "Norway",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 132L,
                            Name = "Oman",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 133L,
                            Name = "Pakistan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 134L,
                            Name = "Palau",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 135L,
                            Name = "Panama",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 136L,
                            Name = "Papua New Guinea",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 137L,
                            Name = "Paraguay",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 138L,
                            Name = "Peru",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 139L,
                            Name = "Philippines",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 140L,
                            Name = "Poland",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 141L,
                            Name = "Portugal",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 142L,
                            Name = "Qatar",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 143L,
                            Name = "Romania",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 144L,
                            Name = "Russia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 145L,
                            Name = "Rwanda",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 146L,
                            Name = "Saint Kitts and Nevis",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 147L,
                            Name = "Saint Lucia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 148L,
                            Name = "Saint Vincent and the Grenadines",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 149L,
                            Name = "Samoa",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 150L,
                            Name = "San Marino",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 151L,
                            Name = "Sao Tome and Principe",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 152L,
                            Name = "Saudi Arabia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 153L,
                            Name = "Senegal",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 154L,
                            Name = "Serbia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 155L,
                            Name = "Seychelles",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 156L,
                            Name = "Sierra Leone",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 157L,
                            Name = "Singapore",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 158L,
                            Name = "Slovakia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 159L,
                            Name = "Slovenia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 160L,
                            Name = "Solomon Islands",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 161L,
                            Name = "Somalia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 162L,
                            Name = "South Africa",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 163L,
                            Name = "South Sudan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 164L,
                            Name = "Spain",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 165L,
                            Name = "Sri Lanka",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 166L,
                            Name = "Sudan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 167L,
                            Name = "Suriname",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 168L,
                            Name = "Swaziland",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 169L,
                            Name = "Sweden",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 170L,
                            Name = "Switzerland",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 171L,
                            Name = "Syria",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 172L,
                            Name = "Taiwan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 173L,
                            Name = "Tajikistan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 174L,
                            Name = "Tanzania",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 175L,
                            Name = "Thailand",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 176L,
                            Name = "Togo",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 177L,
                            Name = "Tonga",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 178L,
                            Name = "Trinidad and Tobago",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 179L,
                            Name = "Tunisia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 180L,
                            Name = "Turkey",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 181L,
                            Name = "Turkmenistan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 182L,
                            Name = "Tuvalu",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 183L,
                            Name = "Uganda",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 184L,
                            Name = "Ukraine",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 185L,
                            Name = "United Arab Emirates",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 186L,
                            Name = "United Kingdom",
                            Order = 1
                        },
                        new
                        {
                            IDCountry = 187L,
                            Name = "United States of America",
                            Order = 1
                        },
                        new
                        {
                            IDCountry = 188L,
                            Name = "Uruguay",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 189L,
                            Name = "Uzbekistan",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 190L,
                            Name = "Vanuatu",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 191L,
                            Name = "Vatican City (Holy See)",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 192L,
                            Name = "Venezuela",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 193L,
                            Name = "Vietnam",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 194L,
                            Name = "Yemen",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 195L,
                            Name = "Zambia",
                            Order = 0
                        },
                        new
                        {
                            IDCountry = 196L,
                            Name = "Zimbabwe",
                            Order = 0
                        });
                });

            modelBuilder.Entity("PSC.Domain.Message", b =>
                {
                    b.Property<long>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMessage");

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
