using Microsoft.EntityFrameworkCore;
using PSC.Domain.CommonTables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PSC.Persistence.Extensions
{
    /// <summary>
    /// Class ModelBuilderExtensions.
    /// </summary>
    public static class ModelBuilderExtensions
    {
        /// <summary>
        /// Seeds the specified model builder.
        /// </summary>
        /// <param name="modelBuilder">The model builder.</param>
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(
                new Country { ID = 1, Name = "Afghanistan" },
                new Country { ID = 2, Name = "Albania" },
                new Country { ID = 3, Name = "Algeria" },
                new Country { ID = 4, Name = "Andorra" },
                new Country { ID = 5, Name = "Angola" },
                new Country { ID = 6, Name = "Antigua and Barbuda" },
                new Country { ID = 7, Name = "Argentina" },
                new Country { ID = 8, Name = "Armenia" },
                new Country { ID = 9, Name = "Australia" },
                new Country { ID = 10, Name = "Austria" },
                new Country { ID = 11, Name = "Azerbaijan" },
                new Country { ID = 12, Name = "The Bahamas" },
                new Country { ID = 13, Name = "Bahrain" },
                new Country { ID = 14, Name = "Bangladesh" },
                new Country { ID = 15, Name = "Barbados" },
                new Country { ID = 16, Name = "Belarus" },
                new Country { ID = 17, Name = "Belgium" },
                new Country { ID = 18, Name = "Belize" },
                new Country { ID = 19, Name = "Benin" },
                new Country { ID = 20, Name = "Bhutan" },
                new Country { ID = 21, Name = "Bolivia" },
                new Country { ID = 22, Name = "Bosnia and Herzegovina" },
                new Country { ID = 23, Name = "Botswana" },
                new Country { ID = 24, Name = "Brazil" },
                new Country { ID = 25, Name = "Brunei" },
                new Country { ID = 26, Name = "Bulgaria" },
                new Country { ID = 27, Name = "Burkina Faso" },
                new Country { ID = 28, Name = "Burundi" },
                new Country { ID = 29, Name = "Cambodia" },
                new Country { ID = 30, Name = "Cameroon" },
                new Country { ID = 31, Name = "Canada" },
                new Country { ID = 32, Name = "Cape Verde" },
                new Country { ID = 33, Name = "Central African Republic" },
                new Country { ID = 34, Name = "Chad" },
                new Country { ID = 35, Name = "Chile" },
                new Country { ID = 36, Name = "China" },
                new Country { ID = 37, Name = "Colombia" },
                new Country { ID = 38, Name = "Comoros" },
                new Country { ID = 39, Name = "Congo, Republic of the" },
                new Country { ID = 40, Name = "Congo, Democratic Republic of the" },
                new Country { ID = 41, Name = "Costa Rica" },
                new Country { ID = 42, Name = "Cote d'Ivoire" },
                new Country { ID = 43, Name = "Croatia" },
                new Country { ID = 44, Name = "Cuba" },
                new Country { ID = 45, Name = "Cyprus" },
                new Country { ID = 46, Name = "Czech Republic" },
                new Country { ID = 47, Name = "Denmark" },
                new Country { ID = 48, Name = "Djibouti" },
                new Country { ID = 49, Name = "Dominica" },
                new Country { ID = 50, Name = "Dominican Republic" },
                new Country { ID = 51, Name = "East Timor (Timor-Leste)" },
                new Country { ID = 52, Name = "Ecuador" },
                new Country { ID = 53, Name = "Egypt" },
                new Country { ID = 54, Name = "El Salvador" },
                new Country { ID = 55, Name = "Equatorial Guinea" },
                new Country { ID = 56, Name = "Eritrea" },
                new Country { ID = 57, Name = "Estonia" },
                new Country { ID = 58, Name = "Ethiopia" },
                new Country { ID = 59, Name = "Fiji" },
                new Country { ID = 60, Name = "Finland" },
                new Country { ID = 61, Name = "France" },
                new Country { ID = 62, Name = "Gabon" },
                new Country { ID = 63, Name = "The Gambia" },
                new Country { ID = 64, Name = "Georgia" },
                new Country { ID = 65, Name = "Germany" },
                new Country { ID = 66, Name = "Ghana" },
                new Country { ID = 67, Name = "Greece" },
                new Country { ID = 68, Name = "Grenada" },
                new Country { ID = 69, Name = "Guatemala" },
                new Country { ID = 70, Name = "Guinea" },
                new Country { ID = 71, Name = "Guinea-Bissau" },
                new Country { ID = 72, Name = "Guyana" },
                new Country { ID = 73, Name = "Haiti" },
                new Country { ID = 74, Name = "Honduras" },
                new Country { ID = 75, Name = "Hungary" },
                new Country { ID = 76, Name = "Iceland" },
                new Country { ID = 77, Name = "India" },
                new Country { ID = 78, Name = "Indonesia" },
                new Country { ID = 79, Name = "Iran" },
                new Country { ID = 80, Name = "Iraq" },
                new Country { ID = 81, Name = "Ireland" },
                new Country { ID = 82, Name = "Israel" },
                new Country { ID = 83, Name = "Italy" },
                new Country { ID = 84, Name = "Jamaica" },
                new Country { ID = 85, Name = "Japan" },
                new Country { ID = 86, Name = "Jordan" },
                new Country { ID = 87, Name = "Kazakhstan" },
                new Country { ID = 88, Name = "Kenya" },
                new Country { ID = 89, Name = "Kiribati" },
                new Country { ID = 90, Name = "Korea, North" },
                new Country { ID = 91, Name = "Korea, South" },
                new Country { ID = 92, Name = "Kosovo" },
                new Country { ID = 93, Name = "Kuwait" },
                new Country { ID = 94, Name = "Kyrgyzstan" },
                new Country { ID = 95, Name = "Laos" },
                new Country { ID = 96, Name = "Latvia" },
                new Country { ID = 97, Name = "Lebanon" },
                new Country { ID = 98, Name = "Lesotho" },
                new Country { ID = 99, Name = "Liberia" },
                new Country { ID = 100, Name = "Libya" },
                new Country { ID = 101, Name = "Liechtenstein" },
                new Country { ID = 102, Name = "Lithuania" },
                new Country { ID = 103, Name = "Luxembourg" },
                new Country { ID = 104, Name = "Macedonia" },
                new Country { ID = 105, Name = "Madagascar" },
                new Country { ID = 106, Name = "Malawi" },
                new Country { ID = 107, Name = "Malaysia" },
                new Country { ID = 108, Name = "Maldives" },
                new Country { ID = 109, Name = "Mali" },
                new Country { ID = 110, Name = "Malta" },
                new Country { ID = 111, Name = "Marshall Islands" },
                new Country { ID = 112, Name = "Mauritania" },
                new Country { ID = 113, Name = "Mauritius" },
                new Country { ID = 114, Name = "Mexico" },
                new Country { ID = 115, Name = "Micronesia, Federated States of" },
                new Country { ID = 116, Name = "Moldova" },
                new Country { ID = 117, Name = "Monaco" },
                new Country { ID = 118, Name = "Mongolia" },
                new Country { ID = 119, Name = "Montenegro" },
                new Country { ID = 120, Name = "Morocco" },
                new Country { ID = 121, Name = "Mozambique" },
                new Country { ID = 122, Name = "Myanmar (Burma)" },
                new Country { ID = 123, Name = "Namibia" },
                new Country { ID = 124, Name = "Nauru" },
                new Country { ID = 125, Name = "Nepal" },
                new Country { ID = 126, Name = "Netherlands" },
                new Country { ID = 127, Name = "New Zealand" },
                new Country { ID = 128, Name = "Nicaragua" },
                new Country { ID = 129, Name = "Niger" },
                new Country { ID = 130, Name = "Nigeria" },
                new Country { ID = 131, Name = "Norway" },
                new Country { ID = 132, Name = "Oman" },
                new Country { ID = 133, Name = "Pakistan" },
                new Country { ID = 134, Name = "Palau" },
                new Country { ID = 135, Name = "Panama" },
                new Country { ID = 136, Name = "Papua New Guinea" },
                new Country { ID = 137, Name = "Paraguay" },
                new Country { ID = 138, Name = "Peru" },
                new Country { ID = 139, Name = "Philippines" },
                new Country { ID = 140, Name = "Poland" },
                new Country { ID = 141, Name = "Portugal" },
                new Country { ID = 142, Name = "Qatar" },
                new Country { ID = 143, Name = "Romania" },
                new Country { ID = 144, Name = "Russia" },
                new Country { ID = 145, Name = "Rwanda" },
                new Country { ID = 146, Name = "Saint Kitts and Nevis" },
                new Country { ID = 147, Name = "Saint Lucia" },
                new Country { ID = 148, Name = "Saint Vincent and the Grenadines" },
                new Country { ID = 149, Name = "Samoa" },
                new Country { ID = 150, Name = "San Marino" },
                new Country { ID = 151, Name = "Sao Tome and Principe" },
                new Country { ID = 152, Name = "Saudi Arabia" },
                new Country { ID = 153, Name = "Senegal" },
                new Country { ID = 154, Name = "Serbia" },
                new Country { ID = 155, Name = "Seychelles" },
                new Country { ID = 156, Name = "Sierra Leone" },
                new Country { ID = 157, Name = "Singapore" },
                new Country { ID = 158, Name = "Slovakia" },
                new Country { ID = 159, Name = "Slovenia" },
                new Country { ID = 160, Name = "Solomon Islands" },
                new Country { ID = 161, Name = "Somalia" },
                new Country { ID = 162, Name = "South Africa" },
                new Country { ID = 163, Name = "South Sudan" },
                new Country { ID = 164, Name = "Spain" },
                new Country { ID = 165, Name = "Sri Lanka" },
                new Country { ID = 166, Name = "Sudan" },
                new Country { ID = 167, Name = "Suriname" },
                new Country { ID = 168, Name = "Swaziland" },
                new Country { ID = 169, Name = "Sweden" },
                new Country { ID = 170, Name = "Switzerland" },
                new Country { ID = 171, Name = "Syria" },
                new Country { ID = 172, Name = "Taiwan" },
                new Country { ID = 173, Name = "Tajikistan" },
                new Country { ID = 174, Name = "Tanzania" },
                new Country { ID = 175, Name = "Thailand" },
                new Country { ID = 176, Name = "Togo" },
                new Country { ID = 177, Name = "Tonga" },
                new Country { ID = 178, Name = "Trinidad and Tobago" },
                new Country { ID = 179, Name = "Tunisia" },
                new Country { ID = 180, Name = "Turkey" },
                new Country { ID = 181, Name = "Turkmenistan" },
                new Country { ID = 182, Name = "Tuvalu" },
                new Country { ID = 183, Name = "Uganda" },
                new Country { ID = 184, Name = "Ukraine" },
                new Country { ID = 185, Name = "United Arab Emirates" },
                new Country { ID = 186, Name = "United Kingdom", Order = 1 },
                new Country { ID = 187, Name = "United States of America", Order = 1 },
                new Country { ID = 188, Name = "Uruguay" },
                new Country { ID = 189, Name = "Uzbekistan" },
                new Country { ID = 190, Name = "Vanuatu" },
                new Country { ID = 191, Name = "Vatican City (Holy See)" },
                new Country { ID = 192, Name = "Venezuela" },
                new Country { ID = 193, Name = "Vietnam" },
                new Country { ID = 194, Name = "Yemen" },
                new Country { ID = 195, Name = "Zambia" },
                new Country { ID = 196, Name = "Zimbabwe" }
            );
        }
    }
}